const codes = [{
  text: 'Shift',
  code: 'ShiftLeft',
  shText: '',
},
{ text: 'Ctrl', code: 'Control', shText: '' },
{ text: 'Caps Lock', code: 'CapsLock', shText: '' },
{ text: 'Alt', code: 'AltLeft', shText: '' },
{ text: 'esc', code: 'Escape', shText: '' },
{ text: 'canc', code: 'Delete', shText: '' },
{ text: 'ENTER', code: 'Enter', shText: '' },
{ text: 'win', code: 'MetaLeft', shText: '' },
{ text: 'Tab', code: 'Tab', shText: '' },
{ text: 'Backspace', code: 'Backspace', shText: '' },
{ text: '\\', code: 'Backquote', shText: 'ё' },
{ text: '1', code: 'Digit1', shText: '!' },
{ text: '2', code: 'Digit2', shText: '@' },
{ text: '3', code: 'Digit3', shText: '#' },
{ text: '4', code: 'Digit4', shText: '$' },
{ text: '5', code: 'Digit5', shText: '%' },
{ text: '6', code: 'Digit6', shText: '&' },
{ text: '7', code: 'Digit7', shText: '/' },
{ text: '8', code: 'Digit8', shText: '(' },
{ text: '9', code: 'Digit9', shText: ')' },
{ text: '0', code: 'Digit0', shText: '=' },
{ text: '?', code: 'Minus', shText: "'" },
{ text: '*', code: 'Equal', shText: '+' },
{ text: 'Q', code: 'KeyQ', shText: 'Й' },
{ text: 'W', code: 'KeyW', shText: 'Ц' },
{ text: 'E', code: 'KeyE', shText: 'У' },
{ text: 'R', code: 'KeyR', shText: 'К' },
{ text: 'T', code: 'KeyT', shText: 'Е' },
{ text: 'Y', code: 'KeyY', shText: 'Н' },
{ text: 'U', code: 'KeyU', shText: 'Г' },
{ text: 'I', code: 'KeyI', shText: 'Ш' },
{ text: 'O', code: 'KeyO', shText: 'Щ' },
{ text: 'P', code: 'KeyP', shText: 'З' },
{ text: '{', code: 'BracketLeft', shText: 'Х' },
{ text: '}', code: 'BracketRight', shText: 'Ъ' },
{ text: '>', code: 'IntlBackslash', shText: '<' },
{ text: 'A', code: 'KeyA', shText: 'Ф' },
{ text: 'S', code: 'KeyS', shText: 'Ы' },
{ text: 'D', code: 'KeyD', shText: 'В' },
{ text: 'F', code: 'KeyF', shText: 'А' },
{ text: 'G', code: 'KeyG', shText: 'П' },
{ text: 'H', code: 'KeyH', shText: 'Р' },
{ text: 'J', code: 'KeyJ', shText: 'О' },
{ text: 'K', code: 'KeyK', shText: 'Л' },
{ text: 'L', code: 'KeyL', shText: 'Д' },
{ text: ':', code: 'Semicolon', shText: 'Ж' },
{ text: '"', code: 'Quote', shText: 'Э' },
{ text: 'Z', code: 'KeyZ', shText: 'Я' },
{ text: 'X', code: 'KeyX', shText: 'Ч' },
{ text: 'C', code: 'KeyC', shText: 'С' },
{ text: 'V', code: 'KeyV', shText: 'М' },
{ text: 'B', code: 'KeyB', shText: 'И' },
{ text: 'N', code: 'KeyN', shText: 'Т' },
{ text: 'M', code: 'KeyM', shText: 'Ь' },
{ text: '~', code: 'Comma', shText: 'Б' },
{ text: ';', code: 'Period', shText: 'Ю' },
{ text: '.', code: 'Slash', shText: ',' },
{ text: '←', code: 'ArrowLeft', shText: '' },
{ text: '↑', code: 'ArrowUp', shText: '' },
{ text: '↓', code: 'ArrowDown', shText: '' },
{ text: '→', code: 'ArrowRight', shText: '' },
{ text: ' ', code: 'Space', shText: '' },
{ text: 'f1', code: 'F1', shText: '' },
{ text: 'f2', code: 'F2', shText: '' },
{ text: 'f3', code: 'F3', shText: '' },
{ text: 'f4', code: 'F4', shText: '' },
{ text: 'f5', code: 'F5', shText: '' },
{ text: 'f6', code: 'F6', shText: '' },
{ text: 'f7', code: 'F7', shText: '' },
{ text: 'f8', code: 'F8', shText: '' },
{ text: 'f9', code: 'F9', shText: '' },
{ text: 'f10', code: 'F10', shText: '' },
{ text: 'f11', code: 'F11', shText: '' },
{ text: 'f12', code: 'F12', shText: '' },
{ text: 'ins', code: 'Insert', shText: '' },
];
export default codes;
